apiVersion: v1
appVersion: "0.6.0"
description: Kubernetes Operator to automatically delete completed Jobs and their Pods by lwolf
name: job-cleanup-operator
version: 0.1.0
author: Carlo Nölle <github:carlonoelle>