# Default values for job-cleanup-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/lwolf/kube-cleanup-operator
  tag: v0.6.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
namespace: default

resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}
