apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "job-cleanup-operator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "job-cleanup-operator.labels" . | indent 4 }}
